// This file is automatically generated by 'configure' - do not edit manually!
#define ARCHITECTURE_x86_64
#define ARCHITECTURE "x86_64"
#define OS_linux
#define OS "linux"
#define CC_gcc
#define CC "gcc"
#define CPPFLAGS ""
#define LDFLAGS ""
#define PREFIX "/usr/local"
#define PACKAGE_VERSION "0.0.0"
