#!/usr/bin/env python3
"""Validate Funky manual page docs against conventions and all_symbols.txt.

Usage:
    tools/validate_existing_pages DOC_PATH
    tools/validate_existing_pages

With one path, validates that single file.
With no arguments, validates all files under docs/symbols/.
Pass a path under docs/topics/ to validate topic pages instead.

A topic page is validated with looser rules than a symbol page:
  * the header is just "# <Topic Name>" (no "(type description)")
  * it must contain at least one Example section
  * every Example must be paired with an Output or Error output section
  * the footer must include the ((generated by ...)) credit line and a
    ((YYYY-MM-DD HH:MM:SS)) timestamp (and the ((defined in ...)) line)
  * "Related topics:" entries must exist under docs/topics/
Symbol-page-only checks (KIND cross-reference, Parameters/Results,
See also, I/O-access warnings) are skipped for topic pages.

Exit 0 if all clean, exit 1 if any issues found.
"""

import re
import sys
import os
from pathlib import Path
from difflib import get_close_matches

BASE = Path(__file__).resolve().parent.parent
SYMBOLS_FILE = BASE / "html" / "all_symbols.txt"
DOCS_DIR = BASE / "docs" / "symbols"
TOPICS_DIR = BASE / "docs" / "topics"

KIND_MAP = {
    "FUNCTION": "a function",
    "IO_FUNCTION": "an I/O-function",
    "POLYMORPHIC_FUNCTION": "a polymorphic function",
    "POLYMORPHIC_FUNCTION_WITH_SETTER": "a polymorphic function with setter",
    "METHOD": "a method",
    "IO_METHOD": "an I/O method",
    "TYPE_FUNCTION": "a type function",
    "UNIQUE_ITEM": "a unique item",
    "CONSTANT": "a constant",
    "VARIABLE": "a variable",
    "ATTRIBUTE": "an attribute",
    "OBJECT": "an object",
}

# Kinds that do not need Parameters/Results sections
NO_PARAMS_RESULTS = {"TYPE", "UNIQUE_ITEM", "CONSTANT", "VARIABLE", "ATTRIBUTE", "TYPE_FUNCTION", "OBJECT"}

# All valid section names as they appear in docs (exact prefix, with colon)
VALID_SECTIONS = [
    "Parameter:", "Parameters:",
    "Options:",
    "Result:", "Results:",
    "Topic:", "Topics:",
    "Example:",
    "Output:",
    "Error output:",
    "See also:",
    "Related topics:",
]

def load_valid_topics():
    """Load valid topic names from docs/topics/ directory."""
    topics = set()
    for entry in os.listdir(DOCS_DIR.parent / "topics"):
        if entry.endswith(".txt"):
            name = entry[:-4].replace("_", " ")
            topics.add(name)
    return topics

# Section patterns for detection (indented with 2 spaces)
SECTION_RE = re.compile(r'^  (' + '|'.join(re.escape(s) for s in VALID_SECTIONS) + r')(.*)$')

IO_WARNING = "**This function must be called with I/O-access rights!**"
IO_PROPAGATION_WARNING = "*This function propagates I/O-access rights to its callback body!*"


def load_symbols():
    """Load html/all_symbols.txt into a dict of symbol_name -> (kind, base)."""
    symbols = {}
    if not SYMBOLS_FILE.exists():
        print(f"  WARN: {SYMBOLS_FILE} not found — skipping KIND checks")
        return symbols
    with open(SYMBOLS_FILE) as f:
        for line in f:
            parts = line.strip().split(None, 3)
            if len(parts) >= 2:
                base = "-" if len(parts) < 3 else parts[2]
                symbols[parts[0]] = (parts[1], base)
    return symbols


def _collect_sections(lines):
    """Return (found_sections, section_counts, example_indices, output_indices)."""
    found_sections = set()
    section_counts = {}
    example_indices = []
    output_indices = []
    for i, line in enumerate(lines):
        sec_match = SECTION_RE.match(line)
        if not sec_match:
            continue
        section_name = sec_match.group(1)
        found_sections.add(section_name)
        section_counts[section_name] = section_counts.get(section_name, 0) + 1
        if section_name == "Example:":
            example_indices.append(i)
        if section_name in ("Output:", "Error output:"):
            output_indices.append(i)
    return found_sections, section_counts, example_indices, output_indices


def _pair_examples_with_outputs(lines):
    """Walk the document sequentially and pair each Example with the output
    section(s) that follow it.

    Returns (example_output_pairs, orphan_outputs):
      example_output_pairs -- number of Examples that have a following
        Output/Error output before the next section closes them
      orphan_outputs -- number of Output/Error output sections not preceded
        by an open Example
    """
    example_output_pairs = 0
    orphan_outputs = 0
    in_example = False
    has_output = False
    for i in range(len(lines)):
        sec_match = SECTION_RE.match(lines[i])
        if not sec_match:
            continue
        section_name = sec_match.group(1)
        if section_name == "Example:":
            if in_example and has_output:
                example_output_pairs += 1
            in_example = True
            has_output = False
        elif section_name in ("Output:", "Error output:"):
            if in_example:
                has_output = True
            else:
                orphan_outputs += 1
        elif in_example:
            if has_output:
                example_output_pairs += 1
            in_example = False
            has_output = False
    if in_example and has_output:
        example_output_pairs += 1
    return example_output_pairs, orphan_outputs


def validate_topic_page(filepath, lines, valid_topics):
    """Validate a topic page under docs/topics/. Returns a list of
    (line_number, message) issue tuples.

    Topic pages use looser rules than symbol pages:
      * the header is just "# <Topic Name>" (no "(type description)")
      * at least one Example section is required
      * every Example must be paired with an Output or Error output section
      * the footer must include the ((generated by ...)) credit line and a
        ((YYYY-MM-DD HH:MM:SS)) timestamp (and the ((defined in ...)) line)
      * "Related topics:" entries must exist under docs/topics/
    """
    issues = []

    # --- Header: "# <Topic Name>" (no parens) ---
    header = lines[0].strip()
    m = re.match(r"^#\s+(\S.*)$", header)
    if not m:
        issues.append((1, f"header not in format '# <Topic Name>': {header}"))
        return issues

    # Blank line after header
    if len(lines) > 1 and lines[1].strip() != "":
        issues.append((2, "missing blank line after header"))

    # --- Collect sections ---
    found_sections, section_counts, _ex_idx, _out_idx = _collect_sections(lines)

    # --- Related topics validation ---
    related_idx = None
    related_raw = None
    for i, line in enumerate(lines):
        sec_match = SECTION_RE.match(line)
        if sec_match and sec_match.group(1) == "Related topics:":
            related_idx = i
            related_raw = sec_match.group(2).strip()
            if i > 0 and lines[i - 1].strip() != "":
                issues.append((i + 1, "'Related topics:' not on fresh paragraph"))
            break
    if related_raw and related_idx is not None:
        for topic in (t.strip() for t in related_raw.split(",") if t.strip()):
            if topic not in valid_topics:
                suggestions = get_close_matches(topic, valid_topics, n=3, cutoff=0.6)
                if suggestions:
                    issues.append((related_idx + 1, f"related topic '{topic}' not found — did you mean: {', '.join(suggestions)}?"))
                else:
                    issues.append((related_idx + 1, f"related topic '{topic}' not found"))

    # --- Example/Output pairing ---
    num_examples = section_counts.get("Example:", 0)
    if num_examples < 1:
        issues.append((0, "missing Example section — topic pages require at least one Example"))
    pairs, orphans = _pair_examples_with_outputs(lines)
    if orphans > 0:
        issues.append((0, f"Example/Output count mismatch: {num_examples} Example(s) but {orphans} orphan Output/Error output section(s) without a preceding Example"))
    elif num_examples > 0 and pairs != num_examples:
        issues.append((0, f"Example/Output count mismatch: {num_examples} Example(s) but {pairs} output pair(s) — each Example must have exactly one Output or Error output"))

    # --- Footer ---
    last_non_blank = []
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip():
            last_non_blank.append((i + 1, lines[i].strip()))
    last_non_blank.reverse()
    footer_lines = [l for _, l in last_non_blank if l.startswith("((")]
    if not footer_lines:
        issues.append((0, "missing footer lines — expected ((defined in ...)), ((generated by ...)), ((timestamp))"))
    else:
        defined = [l for l in footer_lines if l.startswith("((defined in")]
        if not defined:
            issues.append((0, "missing ((defined in ...)) line"))
        elif not defined[0].endswith("))"):
            issues.append((0, f"((defined in ...)) line missing closing )): {defined[0]}"))
        credit = [l for l in footer_lines if "generated by" in l]
        if not credit:
            issues.append((0, "missing credit line ((generated by ...))"))
        elif not credit[0].endswith("))"):
            issues.append((0, f"credit line missing closing )): {credit[0]}"))
        timestamp_lines = [l for _, l in last_non_blank if re.search(r"\d{4}-\d{2}-\d{2}", l)]
        if not timestamp_lines:
            issues.append((0, "missing timestamp line"))
        else:
            ts = timestamp_lines[-1]
            if not re.match(r"^\(\(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\)\)$", ts):
                issues.append((0, f"timestamp not in format ((YYYY-MM-DD HH:MM:SS)): {ts}"))

    # --- Line width ---
    for i, line in enumerate(lines, 1):
        if len(line) > 80:
            issues.append((i, f"line exceeds 80 chars ({len(line)} chars): '{line[:60]}...'"))

    # --- No backticks outside indented code blocks ---
    for i, line in enumerate(lines, 1):
        if line.startswith("    "):
            continue
        if "`" in line:
            issues.append((i, f"backtick found in prose: '{line.strip()}'"))

    # --- No ## markdown headers ---
    for i, line in enumerate(lines, 1):
        if re.match(r"^  ##", line):
            issues.append((i, f"## markdown header found (forbidden): '{line.strip()}'"))

    return issues


def validate_file(filepath, symbols, valid_topics):
    """Return a list of (line_number, message) tuples for a single doc file."""
    issues = []
    f = filepath.relative_to(BASE)

    with open(filepath) as fh:
        content = fh.read()
    lines = content.split("\n")

    if not lines:
        issues.append((0, "empty file"))
        return issues

    header = lines[0].strip()

    # --- Topic page? (loose header, looser rules) ---
    is_topic = TOPICS_DIR in filepath.parents
    if is_topic:
        issues.extend(validate_topic_page(filepath, lines, valid_topics))
        return issues

    # --- Header format ---
    m = re.match(r"^#\s+(.+?)\s+\((.+?)\)$", header)
    if not m:
        issues.append((1, f"header not in format '# symbol_name (type description)': {header}"))
        return issues

    sym = m.group(1)
    kind_text = m.group(2)

    # __ in header (should be ::)
    if "__" in sym:
        issues.append((1, f"symbol name uses __ mangling '{sym}' — should use '::': {sym.replace('__', '::')}"))

    # --- KIND cross-reference ---
    sym_entry = symbols.get(sym)
    if sym_entry:
        sym_kind, sym_base = sym_entry
        if sym_kind == "TYPE":
            expected = "a type" if sym_base == "-" else f"a type derived from {sym_base}"
        else:
            expected = KIND_MAP.get(sym_kind, sym_kind)
        if kind_text != expected:
            issues.append((1, f"header says '{kind_text}' but all_symbols.txt expects '{expected}' ({sym_kind})"))
    else:
        sym_kind = None

    # --- Blank line after header ---
    if len(lines) > 1 and lines[1].strip() != "":
        issues.append((2, "missing blank line after header"))

    # --- Short description must be a single line ---
    # (it is used in generated tables of contents, etc., where a line
    # break produces ugly output)
    if len(lines) > 2 and lines[2].strip():
        paragraph = 1
        i = 3
        while i < len(lines) and lines[i].startswith(" ") and lines[i].strip():
            paragraph += 1
            i += 1
        if paragraph > 1:
            issues.append((4, "short description must be a single line (used in tables of contents, etc.)"))

    # --- Detect section lines and check they are on fresh paragraphs ---
    found_sections = set()
    section_counts = {}  # section_name -> count
    topic_sections = []  # (line_idx, "Topic:"|"Topics:", raw_text)
    example_indices = []  # line indices of "Example:" sections
    output_indices = []   # line indices of "Output:" or "Error output:" sections
    for i in range(len(lines)):
        line = lines[i]
        stripped = line.strip()

        # Check for I/O warning
        if stripped == IO_WARNING:
            if i > 0 and lines[i - 1].strip() != "":
                issues.append((i + 1, f"I/O warning not on fresh paragraph (line {i} is: '{lines[i - 1].strip()}')"))
            found_sections.add("I/O warning")
            continue

        # Check for I/O propagation warning
        if stripped == IO_PROPAGATION_WARNING:
            if i > 0 and lines[i - 1].strip() != "":
                issues.append((i + 1, f"I/O propagation warning not on fresh paragraph (line {i} is: '{lines[i - 1].strip()}')"))
            found_sections.add("I/O propagation")
            continue

        # Check for valid section names
        sec_match = SECTION_RE.match(line)
        if sec_match:
            section_name = sec_match.group(1)
            found_sections.add(section_name)
            section_counts[section_name] = section_counts.get(section_name, 0) + 1
            if section_name == "Example:":
                example_indices.append(i)
            if section_name in ("Output:", "Error output:"):
                output_indices.append(i)
            if i > 0 and lines[i - 1].strip() != "":
                issues.append((i + 1, f"'{section_name}' not on fresh paragraph (line {i} is: '{lines[i - 1].strip()}')"))
            # Blank line must follow Example: before code begins
            if section_name == "Example:":
                j = i + 1
                while j < len(lines) and lines[j].strip() == "":
                    j += 1
                if j < len(lines) and not lines[j].startswith("    "):
                    # next content is not indented code — ok (e.g., text after Example:)
                    pass
                elif j >= len(lines):
                    # nothing after Example:
                    pass
                else:
                    # code follows — check there's a blank line between
                    if lines[i + 1].strip() != "":
                        issues.append((i + 2, "missing blank line after 'Example:' — code must be separated by a blank line"))
            if section_name in ("Topic:", "Topics:"):
                topic_sections.append((i, section_name, sec_match.group(2).strip()))
            continue

        # Detect possible section typos: line starts with 2 spaces, contains ':',
        # and doesn't match any valid section, parameter value, or code
        trimmed = stripped.rstrip()
        if line.startswith("  ") and not line.startswith("    ") and ":" in trimmed:
            candidate = trimmed
            # Skip if it looks like a parameter/result value (indented further or contains ': ')
            if not trimmed.startswith("*"):
                # Check if it's close to a valid section name
                for valid in VALID_SECTIONS:
                    if candidate.startswith(valid):
                        break
                else:
                    # Not a valid section prefix — check for typo
                    close = get_close_matches(candidate, VALID_SECTIONS, n=1, cutoff=0.8)
                    if close:
                        issues.append((i + 1, f"possible section name typo '{candidate}' — did you mean '{close[0]}'?"))

    # --- Validate topics ---
    for i, sec_name, raw_text in topic_sections:
        topics = [t.strip() for t in raw_text.split(",")]
        if sec_name == "Topic:":
            if len(topics) > 1:
                issues.append((i + 1, f"Topic: allows only one topic (got {len(topics)}), use Topics: instead"))
        elif sec_name == "Topics:":
            if len(topics) < 2:
                issues.append((i + 1, f"Topics: requires two or more (got {len(topics)}), use Topic: instead"))
        for topic in topics:
            if topic not in valid_topics:
                suggestions = get_close_matches(topic, valid_topics, n=3, cutoff=0.6)
                if suggestions:
                    issues.append((i + 1, f"topic '{topic}' not found — did you mean: {', '.join(suggestions)}?"))
                else:
                    issues.append((i + 1, f"topic '{topic}' not found"))

    # --- Validate Example/Output pairing ---
    # Walk document sequentially, pairing each Example with the section(s) that follow.
    # An Example followed by Output: alone OR Error output: alone = one pair.
    # An Example followed by Output: AND Error output: (consecutively) = one "Both" pair.
    # A pair is CLOSED by the next Example, another section, or end of file.
    example_output_pairs = 0
    orphan_outputs = 0
    in_example = False
    has_output = False
    for i in range(len(lines)):
        sec_match = SECTION_RE.match(lines[i])
        if sec_match:
            section_name = sec_match.group(1)
            if section_name == "Example:":
                if in_example and has_output:
                    example_output_pairs += 1  # close previous pair
                in_example = True
                has_output = False
            elif section_name in ("Output:", "Error output:"):
                if in_example:
                    has_output = True  # mark that this Example has output (don't count yet)
                else:
                    orphan_outputs += 1
            elif in_example:
                # Another section before any output — close pair with no output
                if has_output:
                    example_output_pairs += 1
                in_example = False
                has_output = False
    # Close final pair if still open
    if in_example and has_output:
        example_output_pairs += 1

    num_examples = section_counts.get("Example:", 0)
    if orphan_outputs > 0:
        issues.append((0, f"Example/Output count mismatch: {num_examples} Example(s) but {orphan_outputs} orphan Output/Error output section(s) without a preceding Example"))
    elif num_examples > 0 and example_output_pairs != num_examples:
        issues.append((0, f"Example/Output count mismatch: {num_examples} Example(s) but {example_output_pairs} output pair(s) — each Example must have exactly one Output or Error output"))

    # --- Required sections presence ---
    has_parameter = "Parameter:" in found_sections or "Parameters:" in found_sections
    has_result = "Result:" in found_sections or "Results:" in found_sections
    has_example = "Example:" in found_sections
    has_output = "Output:" in found_sections or "Error output:" in found_sections
    has_topic = "Topic:" in found_sections or "Topics:" in found_sections
    has_see_also = "See also:" in found_sections
    has_io_warning = "I/O warning" in found_sections
    has_io_propagation = "I/O propagation" in found_sections

    is_io = "I/O-function" in header or "I/O method" in header
    needs_params_results = sym_kind not in NO_PARAMS_RESULTS

    if needs_params_results:
        if not has_parameter:
            issues.append((0, "missing Parameters/Parameter section"))
        if not has_result:
            issues.append((0, "missing Results/Result section"))
        if not has_example:
            issues.append((0, "missing Example section"))
        if not has_output:
            issues.append((0, "missing Output/Error output section"))
    if not has_topic:
        issues.append((0, "missing Topic/Topics section"))
    if not has_see_also:
        issues.append((0, "missing See also section"))

    # --- I/O warning presence ---
    if (has_io_warning or has_io_propagation) and not is_io:
        issues.append((0, "has I/O-access warning but KIND is not I/O"))
    if is_io and not (has_io_warning or has_io_propagation):
        issues.append((0, "KIND is I/O but missing I/O-access rights warning"))

    # --- I/O warning placement (must be AFTER Results) ---
    if has_io_warning or has_io_propagation:
        io_line_idx = None
        for i, line in enumerate(lines):
            if line.strip() == IO_WARNING or line.strip() == IO_PROPAGATION_WARNING:
                io_line_idx = i
                break
        result_line_idx = None
        for i, line in enumerate(lines):
            if SECTION_RE.match(line):
                sec = SECTION_RE.match(line).group(1)
                if sec in ("Result:", "Results:"):
                    result_line_idx = i
                    break
        if result_line_idx is not None and io_line_idx is not None:
            if io_line_idx < result_line_idx:
                issues.append((0, "I/O-access warning appears before Results section"))

    # --- Results section followed by blank line ---
    for i in range(len(lines)):
        sec_match = SECTION_RE.match(lines[i])
        if sec_match and sec_match.group(1) in ("Result:", "Results:"):
            j = i + 1
            while j < len(lines) and lines[j].startswith("    "):
                j += 1
            if j < len(lines) and lines[j].strip() != "":
                issues.append((j + 1, f"Result value on line {i+1} not followed by blank line (line {j+1} is: '{lines[j].strip()}')"))

    # --- Section headers immediately followed by a blank line ---
    # The first content of a Parameter/Parameters/Result/Results section must
    # start on the line right after the header.
    for i in range(len(lines) - 1):
        sec_match = SECTION_RE.match(lines[i])
        if (sec_match and sec_match.group(1) in ("Parameter:", "Parameters:",
                                                 "Result:", "Results:")
                and lines[i + 1].strip() == ""):
            issues.append((i + 2, f"'{sec_match.group(1)}' section header followed by blank line"))

    # --- Footer format ---
    last_non_blank = []
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip():
            last_non_blank.append((i + 1, lines[i].strip()))
    last_non_blank.reverse()

    # Any line starting with (( is a footer candidate
    footer_lines = [l for _, l in last_non_blank if l.startswith("((")]

    if not footer_lines:
        issues.append((0, "missing footer lines — expected ((defined in ...)), ((generated by ...)), ((timestamp))"))
    else:
        defined = [l for l in footer_lines if l.startswith("((defined in")]
        if not defined:
            issues.append((0, "missing ((defined in ...)) line"))
        elif not defined[0].endswith("))"):
            issues.append((0, f"((defined in ...)) line missing closing )): {defined[0]}"))

        credit = [l for l in footer_lines if "generated by" in l]
        if not credit:
            issues.append((0, "missing credit line ((generated by ...))"))
        elif not credit[0].endswith("))"):
            issues.append((0, f"credit line missing closing )): {credit[0]}"))

        # Timestamp: check all last non-blank lines for date pattern
        timestamp_lines = [l for _, l in last_non_blank if re.search(r"\d{4}-\d{2}-\d{2}", l)]
        if not timestamp_lines:
            issues.append((0, "missing timestamp line"))
        else:
            ts = timestamp_lines[-1]
            if not re.match(r"^\(\(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\)\)$", ts):
                issues.append((0, f"timestamp not in format ((YYYY-MM-DD HH:MM:SS)): {ts}"))

    # --- Line width ---
    for i, line in enumerate(lines, 1):
        if len(line) > 80:
            issues.append((i, f"line exceeds 80 chars ({len(line)} chars): '{line[:60]}...'"))

    # --- No backticks outside indented code blocks ---
    for i, line in enumerate(lines, 1):
        if line.startswith("    "):
            continue
        if "`" in line:
            issues.append((i, f"backtick found in prose: '{line.strip()}'"))

    # --- No ## markdown headers ---
    for i, line in enumerate(lines, 1):
        if re.match(r"^  ##", line):
            issues.append((i, f"## markdown header found (forbidden): '{line.strip()}'"))

    return issues


def collect_doc_files(paths):
    """Collect doc files from explicit paths or all of docs/symbols/.

    Explicit paths may be individual .txt files or directories (which are
    scanned recursively for .txt files). With no arguments, all of
    docs/symbols/ is validated.
    """
    if paths:
        files = []
        for p in paths:
            fp = BASE / p
            if fp.is_file():
                files.append(fp)
            elif fp.is_dir():
                files.extend(sorted(fp.rglob("*.txt")))
            else:
                print(f"  ERROR: file not found: {p}")
        return files
    else:
        # Default: validate all symbol pages and all topic pages.
        return sorted(DOCS_DIR.rglob("*.txt")) + sorted(TOPICS_DIR.rglob("*.txt"))


def main():
    paths = sys.argv[1:] if len(sys.argv) > 1 else []
    symbols = load_symbols()
    valid_topics = load_valid_topics()
    files = collect_doc_files(paths)

    if not files:
        print("No doc files found.")
        return 1

    all_issues = []
    files_ok = 0
    files_bad = 0

    for filepath in files:
        issues = validate_file(filepath, symbols, valid_topics)
        if issues:
            files_bad += 1
            all_issues.append((filepath, issues))
        else:
            files_ok += 1

    if all_issues:
        for filepath, issues in all_issues:
            f = filepath.relative_to(BASE)
            print(f"{f}:")
            for line_num, msg in issues:
                if line_num == 0:
                    print(f"  ISSUE: {msg}")
                else:
                    print(f"  {line_num}: {msg}")
        print(f"\n{files_ok}/{len(files)} files OK, {files_bad} with issues")
        return 1
    else:
        print(f"All {len(files)} file{'s' if len(files) != 1 else ''} OK.")
        return 0


if __name__ == "__main__":
    sys.exit(main())